/**
 * The built-in sport registry.
 *
 * Every entry is plain data. The tournament engine reads these records and has
 * no knowledge of any specific sport, so adding one here — or letting an
 * organizer define one at runtime — needs no engine change.
 */

import type { PointsRule, SportConfig, StatKey, Tiebreaker } from '@/types'

/** Points systems shared by several sports, named for readability. */
const POINTS: Record<string, PointsRule> = {
  /** 3 for a win, 1 for a draw — the modern football standard. */
  football: { win: 3, draw: 1, loss: 0, noResult: 1 },
  /** 2 for a win, no draws possible. */
  winTwo: { win: 2, draw: 1, loss: 0, noResult: 1 },
  /** 1 for a win — used where win% is the real ranking metric. */
  winOne: { win: 1, draw: 0, loss: 0, noResult: 0 },
  /** Volleyball-style: 3 for a straight win, 2 if it goes the distance. */
  volleyball: { win: 3, draw: 0, loss: 0, noResult: 1 },
}

/** Tiebreaker chains, likewise named. */
const TIEBREAK: Record<string, Tiebreaker[]> = {
  goalDifference: [
    { key: 'points', dir: 'desc' },
    { key: 'scoreDiff', dir: 'desc' },
    { key: 'scoreFor', dir: 'desc' },
    { key: 'headToHead', dir: 'desc' },
    { key: 'won', dir: 'desc' },
    { key: 'name', dir: 'asc' },
  ],
  pointDifference: [
    { key: 'winPct', dir: 'desc' },
    { key: 'won', dir: 'desc' },
    { key: 'headToHead', dir: 'desc' },
    { key: 'scoreDiff', dir: 'desc' },
    { key: 'scoreFor', dir: 'desc' },
    { key: 'name', dir: 'asc' },
  ],
  netRunRate: [
    { key: 'points', dir: 'desc' },
    { key: 'nrr', dir: 'desc' },
    { key: 'won', dir: 'desc' },
    { key: 'headToHead', dir: 'desc' },
    { key: 'name', dir: 'asc' },
  ],
  setRatio: [
    { key: 'points', dir: 'desc' },
    { key: 'won', dir: 'desc' },
    { key: 'setsDiff', dir: 'desc' },
    { key: 'scoreDiff', dir: 'desc' },
    { key: 'headToHead', dir: 'desc' },
    { key: 'name', dir: 'asc' },
  ],
}

/** Standings column sets. */
const COLUMNS: Record<string, StatKey[]> = {
  football: ['played', 'won', 'drawn', 'lost', 'scoreFor', 'scoreAgainst', 'scoreDiff', 'points'],
  basketball: ['played', 'won', 'lost', 'winPct', 'scoreFor', 'scoreAgainst', 'scoreDiff', 'points'],
  cricket: ['played', 'won', 'lost', 'noResult', 'nrr', 'points'],
  sets: ['played', 'won', 'lost', 'setsFor', 'setsAgainst', 'setsDiff', 'scoreDiff', 'points'],
  simple: ['played', 'won', 'lost', 'scoreFor', 'scoreAgainst', 'scoreDiff', 'points'],
}

export const BUILT_IN_SPORTS: SportConfig[] = [
  {
    id: 'football',
    name: 'Football',
    shortName: 'FTB',
    icon: '⚽',
    lucideIcon: 'Goal',
    participantType: 'team',
    scoringType: 'aggregate',
    teamSize: 11,
    squadSize: 23,
    periods: { count: 2, label: 'Half', durationMinutes: 45, setsToWin: null, pointsPerSet: null },
    matchDurationMinutes: 105,
    allowsDraw: true,
    drawResolution: 'shootout',
    drawResolutionLabel: 'Penalties',
    pointsRule: POINTS.football,
    standingsColumns: COLUMNS.football,
    tiebreakers: TIEBREAK.goalDifference,
    scoreNoun: ['goal', 'goals'],
    positions: ['GK', 'DF', 'MF', 'FW'],
    officialRoles: ['Referee', 'Assistant Referee', 'Fourth Official'],
    builtIn: true,
  },
  {
    id: 'futsal',
    name: 'Futsal',
    shortName: 'FSL',
    icon: '🥅',
    lucideIcon: 'Goal',
    participantType: 'team',
    scoringType: 'aggregate',
    teamSize: 5,
    squadSize: 14,
    periods: { count: 2, label: 'Half', durationMinutes: 20, setsToWin: null, pointsPerSet: null },
    matchDurationMinutes: 60,
    allowsDraw: true,
    drawResolution: 'shootout',
    drawResolutionLabel: 'Penalties',
    pointsRule: POINTS.football,
    standingsColumns: COLUMNS.football,
    tiebreakers: TIEBREAK.goalDifference,
    scoreNoun: ['goal', 'goals'],
    positions: ['GK', 'DF', 'WG', 'PV'],
    officialRoles: ['Referee', 'Second Referee', 'Timekeeper'],
    builtIn: true,
  },
  {
    id: 'cricket',
    name: 'Cricket',
    shortName: 'CRK',
    icon: '🏏',
    lucideIcon: 'Target',
    participantType: 'team',
    scoringType: 'innings',
    teamSize: 11,
    squadSize: 16,
    periods: { count: 1, label: 'Innings', durationMinutes: 90, setsToWin: null, pointsPerSet: null },
    matchDurationMinutes: 210,
    allowsDraw: false,
    drawResolution: 'super_over',
    drawResolutionLabel: 'Super Over',
    pointsRule: POINTS.winTwo,
    standingsColumns: COLUMNS.cricket,
    tiebreakers: TIEBREAK.netRunRate,
    scoreNoun: ['run', 'runs'],
    positions: ['Batter', 'Bowler', 'All-rounder', 'Wicket-keeper'],
    officialRoles: ['Umpire', 'Third Umpire', 'Scorer', 'Match Referee'],
    builtIn: true,
  },
  {
    id: 'basketball',
    name: 'Basketball',
    shortName: 'BKB',
    icon: '🏀',
    lucideIcon: 'CircleDot',
    participantType: 'team',
    scoringType: 'aggregate',
    teamSize: 5,
    squadSize: 12,
    periods: { count: 4, label: 'Quarter', durationMinutes: 10, setsToWin: null, pointsPerSet: null },
    matchDurationMinutes: 90,
    allowsDraw: false,
    drawResolution: 'extra_period',
    drawResolutionLabel: 'Overtime',
    pointsRule: POINTS.winTwo,
    standingsColumns: COLUMNS.basketball,
    tiebreakers: TIEBREAK.pointDifference,
    scoreNoun: ['point', 'points'],
    positions: ['PG', 'SG', 'SF', 'PF', 'C'],
    officialRoles: ['Crew Chief', 'Referee', 'Umpire', 'Scorer'],
    builtIn: true,
  },
  {
    id: 'volleyball',
    name: 'Volleyball',
    shortName: 'VLB',
    icon: '🏐',
    lucideIcon: 'Volleyball',
    participantType: 'team',
    scoringType: 'sets',
    teamSize: 6,
    squadSize: 14,
    periods: { count: 5, label: 'Set', durationMinutes: 25, setsToWin: 3, pointsPerSet: 25 },
    matchDurationMinutes: 120,
    allowsDraw: false,
    drawResolution: 'none',
    drawResolutionLabel: '',
    pointsRule: POINTS.volleyball,
    standingsColumns: COLUMNS.sets,
    tiebreakers: TIEBREAK.setRatio,
    scoreNoun: ['point', 'points'],
    positions: ['Setter', 'Outside Hitter', 'Opposite', 'Middle Blocker', 'Libero'],
    officialRoles: ['First Referee', 'Second Referee', 'Scorer', 'Line Judge'],
    builtIn: true,
  },
  {
    id: 'badminton',
    name: 'Badminton',
    shortName: 'BDM',
    icon: '🏸',
    lucideIcon: 'Zap',
    participantType: 'individual',
    scoringType: 'sets',
    teamSize: 1,
    squadSize: 1,
    periods: { count: 3, label: 'Game', durationMinutes: 20, setsToWin: 2, pointsPerSet: 21 },
    matchDurationMinutes: 45,
    allowsDraw: false,
    drawResolution: 'none',
    drawResolutionLabel: '',
    pointsRule: POINTS.winOne,
    standingsColumns: COLUMNS.sets,
    tiebreakers: TIEBREAK.setRatio,
    scoreNoun: ['point', 'points'],
    positions: ['Singles', 'Doubles'],
    officialRoles: ['Umpire', 'Service Judge', 'Line Judge'],
    builtIn: true,
  },
  {
    id: 'table_tennis',
    name: 'Table Tennis',
    shortName: 'TTN',
    icon: '🏓',
    lucideIcon: 'Zap',
    participantType: 'individual',
    scoringType: 'sets',
    teamSize: 1,
    squadSize: 1,
    periods: { count: 5, label: 'Game', durationMinutes: 8, setsToWin: 3, pointsPerSet: 11 },
    matchDurationMinutes: 40,
    allowsDraw: false,
    drawResolution: 'none',
    drawResolutionLabel: '',
    pointsRule: POINTS.winOne,
    standingsColumns: COLUMNS.sets,
    tiebreakers: TIEBREAK.setRatio,
    scoreNoun: ['point', 'points'],
    positions: ['Singles', 'Doubles'],
    officialRoles: ['Umpire', 'Assistant Umpire'],
    builtIn: true,
  },
  {
    id: 'tennis',
    name: 'Tennis',
    shortName: 'TNS',
    icon: '🎾',
    lucideIcon: 'CircleDot',
    participantType: 'individual',
    scoringType: 'sets',
    teamSize: 1,
    squadSize: 1,
    periods: { count: 3, label: 'Set', durationMinutes: 40, setsToWin: 2, pointsPerSet: 6 },
    matchDurationMinutes: 120,
    allowsDraw: false,
    drawResolution: 'none',
    drawResolutionLabel: '',
    pointsRule: POINTS.winOne,
    standingsColumns: COLUMNS.sets,
    tiebreakers: TIEBREAK.setRatio,
    scoreNoun: ['game', 'games'],
    positions: ['Singles', 'Doubles'],
    officialRoles: ['Chair Umpire', 'Line Judge'],
    builtIn: true,
  },
  {
    id: 'esports',
    name: 'Esports',
    shortName: 'ESP',
    icon: '🎮',
    lucideIcon: 'Gamepad2',
    participantType: 'team',
    scoringType: 'sets',
    teamSize: 5,
    squadSize: 8,
    periods: { count: 3, label: 'Map', durationMinutes: 35, setsToWin: 2, pointsPerSet: null },
    matchDurationMinutes: 120,
    allowsDraw: false,
    drawResolution: 'none',
    drawResolutionLabel: '',
    pointsRule: POINTS.winOne,
    standingsColumns: COLUMNS.sets,
    tiebreakers: TIEBREAK.setRatio,
    scoreNoun: ['round', 'rounds'],
    positions: ['Captain', 'Player', 'Substitute', 'Coach'],
    officialRoles: ['Referee', 'Admin', 'Observer'],
    builtIn: true,
  },
]

/** Starting point for the custom-sport builder — a neutral team sport. */
export const CUSTOM_SPORT_TEMPLATE: Omit<SportConfig, 'id' | 'builtIn'> = {
  name: '',
  shortName: '',
  icon: '🏆',
  lucideIcon: 'Trophy',
  participantType: 'team',
  scoringType: 'aggregate',
  teamSize: 5,
  squadSize: 12,
  periods: { count: 2, label: 'Half', durationMinutes: 20, setsToWin: null, pointsPerSet: null },
  matchDurationMinutes: 60,
  allowsDraw: true,
  drawResolution: 'shootout',
  drawResolutionLabel: 'Tiebreak',
  pointsRule: { win: 3, draw: 1, loss: 0, noResult: 1 },
  standingsColumns: COLUMNS.simple,
  tiebreakers: TIEBREAK.goalDifference,
  scoreNoun: ['point', 'points'],
  positions: ['Player'],
  officialRoles: ['Referee'],
}

/** Every stat key with the label and formatting the UI should use for it. */
export const STAT_META: Record<
  StatKey,
  { label: string; full: string; format: 'int' | 'signed' | 'pct' | 'decimal3'; emphasize?: boolean }
> = {
  played: { label: 'P', full: 'Played', format: 'int' },
  won: { label: 'W', full: 'Won', format: 'int' },
  drawn: { label: 'D', full: 'Drawn', format: 'int' },
  lost: { label: 'L', full: 'Lost', format: 'int' },
  noResult: { label: 'NR', full: 'No Result', format: 'int' },
  scoreFor: { label: 'F', full: 'For', format: 'int' },
  scoreAgainst: { label: 'A', full: 'Against', format: 'int' },
  scoreDiff: { label: 'Diff', full: 'Difference', format: 'signed' },
  setsFor: { label: 'SW', full: 'Sets Won', format: 'int' },
  setsAgainst: { label: 'SL', full: 'Sets Lost', format: 'int' },
  setsDiff: { label: 'SD', full: 'Set Difference', format: 'signed' },
  points: { label: 'PTS', full: 'Points', format: 'int', emphasize: true },
  winPct: { label: 'PCT', full: 'Win %', format: 'pct' },
  nrr: { label: 'NRR', full: 'Net Run Rate', format: 'decimal3' },
  streak: { label: 'STRK', full: 'Streak', format: 'signed' },
}

/**
 * Sport-aware header overrides. `scoreFor`/`scoreAgainst`/`scoreDiff` mean
 * different things per sport, and organizers expect the familiar abbreviation.
 */
export const SPORT_STAT_LABELS: Record<string, Partial<Record<StatKey, string>>> = {
  football: { scoreFor: 'GF', scoreAgainst: 'GA', scoreDiff: 'GD' },
  futsal: { scoreFor: 'GF', scoreAgainst: 'GA', scoreDiff: 'GD' },
  basketball: { scoreFor: 'PF', scoreAgainst: 'PA', scoreDiff: 'PD' },
  cricket: { scoreFor: 'RF', scoreAgainst: 'RA', scoreDiff: 'RD' },
  volleyball: { scoreFor: 'PF', scoreAgainst: 'PA', scoreDiff: 'PD' },
  badminton: { scoreFor: 'PF', scoreAgainst: 'PA', scoreDiff: 'PD' },
  table_tennis: { scoreFor: 'PF', scoreAgainst: 'PA', scoreDiff: 'PD' },
  tennis: { scoreFor: 'GF', scoreAgainst: 'GA', scoreDiff: 'GD' },
  esports: { scoreFor: 'RF', scoreAgainst: 'RA', scoreDiff: 'RD' },
}

/** Resolve the column header for a stat, honouring sport-specific naming. */
export function statLabel(key: StatKey, sportId?: string): string {
  if (sportId && SPORT_STAT_LABELS[sportId]?.[key]) return SPORT_STAT_LABELS[sportId][key] as string
  return STAT_META[key].label
}
